apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-webapp
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: nginx-container
        image: abdelrahman404/my-nginx-webapp:1.0
        ports:
        - containerPort: 80